version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: sweetshop_db
    environment:
      POSTGRES_USER: sweetshop
      POSTGRES_PASSWORD: sweetshop123
      POSTGRES_DB: sweetshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sweetshop"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sweetshop_backend
    environment:
      DATABASE_URL: "postgresql://sweetshop:sweetshop123@db:5432/sweetshop_db?schema=public"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      JWT_EXPIRES_IN: "7d"
      PORT: 5000
      NODE_ENV: "production"
      FRONTEND_URL: "http://localhost:3000"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sweetshop_frontend
    environment:
      VITE_API_URL: "http://localhost:5000/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
